export const BUTTON_CLICKED = 'BUTTON_CLICKED';
export const BAR_CHANGED = 'BAR_CHANGED';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';